# Generated by Django 2.2 on 2019-05-22 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('site', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tecnum', models.IntegerField()),
                ('teanum', models.IntegerField()),
                ('fnum', models.IntegerField()),
                ('stime', models.DateTimeField()),
                ('etime', models.DateTimeField()),
                ('site', models.CharField(max_length=15)),
                ('allo', models.FloatField(default=180)),
                ('apply', models.FloatField(default=1500)),
                ('comm', models.TextField(max_length=300)),
                ('ac_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.Acc')),
            ],
        ),
        migrations.CreateModel(
            name='Admi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=20)),
                ('ty', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EAir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_id', models.CharField(max_length=15)),
                ('stime', models.DateTimeField()),
                ('etime', models.DateTimeField()),
                ('price', models.FloatField()),
                ('site', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Eleb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tecnum', models.IntegerField()),
                ('teanum', models.IntegerField()),
                ('fnum', models.IntegerField()),
                ('stime', models.DateTimeField()),
                ('etime', models.DateTimeField()),
                ('site', models.CharField(max_length=15)),
                ('allo', models.FloatField(default=180)),
                ('apply', models.FloatField(default=1500)),
                ('ac_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.Acc')),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.Admi')),
                ('eai_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.EAir')),
            ],
        ),
        migrations.CreateModel(
            name='ETra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_id', models.CharField(max_length=15)),
                ('stime', models.DateTimeField()),
                ('etime', models.DateTimeField()),
                ('price', models.FloatField()),
                ('site', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SAir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_id', models.CharField(max_length=15)),
                ('stime', models.DateTimeField()),
                ('etime', models.DateTimeField()),
                ('price', models.FloatField()),
                ('site', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='STra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_id', models.CharField(max_length=15)),
                ('stime', models.DateTimeField()),
                ('etime', models.DateTimeField()),
                ('price', models.FloatField()),
                ('site', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Ultb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tecnum', models.IntegerField()),
                ('teanum', models.IntegerField()),
                ('fnum', models.IntegerField()),
                ('stime', models.DateTimeField()),
                ('etime', models.DateTimeField()),
                ('site', models.CharField(max_length=15)),
                ('allo', models.FloatField(default=180)),
                ('apply', models.FloatField(default=1500)),
                ('ac_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.Acc')),
                ('ad_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.Admi')),
                ('eai_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.EAir')),
                ('el_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.Eleb')),
                ('etr_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.ETra')),
                ('sai_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.SAir')),
                ('str_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.STra')),
            ],
        ),
        migrations.CreateModel(
            name='LoginAdmi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.Admi')),
            ],
        ),
        migrations.AddField(
            model_name='eleb',
            name='etr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.ETra'),
        ),
        migrations.AddField(
            model_name='eleb',
            name='sai_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.SAir'),
        ),
        migrations.AddField(
            model_name='eleb',
            name='str_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.STra'),
        ),
        migrations.CreateModel(
            name='CName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ac_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Account')),
                ('el_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.Eleb')),
                ('ul_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.Ultb')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='ad_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.Admi'),
        ),
        migrations.AddField(
            model_name='account',
            name='eai_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.EAir'),
        ),
        migrations.AddField(
            model_name='account',
            name='etr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.ETra'),
        ),
        migrations.AddField(
            model_name='account',
            name='sai_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.SAir'),
        ),
        migrations.AddField(
            model_name='account',
            name='str_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.STra'),
        ),
        migrations.AddField(
            model_name='account',
            name='ul_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budget.Ultb'),
        ),
    ]
