from django.db import models

class STra(models.Model):
    T_id = models.CharField(max_length=15)
    stime = models.DateTimeField()
    etime = models.DateTimeField()
    price = models.FloatField()
    site = models.CharField(max_length=15)
class ETra(models.Model):
    T_id = models.CharField(max_length=15)
    stime = models.DateTimeField()
    etime = models.DateTimeField()
    price = models.FloatField()
    site = models.CharField(max_length=15)
class Acc(models.Model):
    name = models.CharField(max_length=50)
    price = models.FloatField()
    site = models.CharField(max_length=15)
class SAir(models.Model):
    A_id = models.CharField(max_length=15)
    stime = models.DateTimeField()
    etime = models.DateTimeField()
    price = models.FloatField()
    site = models.CharField(max_length=15)

class EAir(models.Model):
    A_id = models.CharField(max_length=15)
    stime = models.DateTimeField()
    etime = models.DateTimeField()
    price = models.FloatField()
    site = models.CharField(max_length=15)

class Admi(models.Model):
    name = models.CharField(max_length=15)
    password = models.CharField(max_length=20)
    ty = models.BooleanField(default=False)

class LoginAdmi(models.Model):
    user = models.ForeignKey(Admi, on_delete=models.DO_NOTHING)
class Eleb(models.Model):
    name = models.CharField(max_length=30)
    tecnum = models.IntegerField()
    teanum = models.IntegerField()
    fnum = models.IntegerField()
    stime = models.DateTimeField()
    etime = models.DateTimeField()
    site = models.CharField(max_length=15)
    allo = models.FloatField(default=180)
    apply = models.FloatField(default=1500)
    str_id = models.ForeignKey(STra, on_delete=models.DO_NOTHING)
    etr_id = models.ForeignKey(ETra, on_delete=models.DO_NOTHING)
    sai_id = models.ForeignKey(SAir, on_delete=models.SET_NULL, null=True)
    eai_id = models.ForeignKey(EAir, on_delete=models.SET_NULL, null=True)
    ac_id = models.ForeignKey(Acc, on_delete=models.DO_NOTHING)
    ad_id = models.ForeignKey(Admi, on_delete=models.DO_NOTHING)
class Ultb(models.Model):
    name = models.CharField(max_length=30)
    tecnum = models.IntegerField()
    teanum = models.IntegerField()
    fnum = models.IntegerField()
    stime = models.DateTimeField()
    etime = models.DateTimeField()
    site = models.CharField(max_length=15)
    allo = models.FloatField(default=180)
    apply = models.FloatField(default=1500)
    str_id = models.ForeignKey(STra, on_delete=models.DO_NOTHING)
    etr_id = models.ForeignKey(ETra, on_delete=models.DO_NOTHING)
    sai_id = models.ForeignKey(SAir, on_delete=models.SET_NULL, null=True)
    eai_id = models.ForeignKey(EAir, on_delete=models.SET_NULL, null=True)
    ac_id = models.ForeignKey(Acc, on_delete=models.DO_NOTHING)
    ad_id = models.ForeignKey(Admi, on_delete=models.DO_NOTHING)
    el_id = models.ForeignKey(Eleb, on_delete=models.DO_NOTHING)
class Account(models.Model):
    name = models.CharField(max_length=30)
    tecnum = models.IntegerField()
    teanum = models.IntegerField()
    fnum = models.IntegerField()
    stime = models.DateTimeField()
    etime = models.DateTimeField()
    site = models.CharField(max_length=15)
    allo = models.FloatField(default=180)
    apply = models.FloatField(default=1500)
    str_id = models.ForeignKey(STra, on_delete=models.DO_NOTHING)
    etr_id = models.ForeignKey(ETra, on_delete=models.DO_NOTHING)
    sai_id = models.ForeignKey(SAir, on_delete=models.SET_NULL, null=True)
    eai_id = models.ForeignKey(EAir, on_delete=models.SET_NULL, null=True)
    ac_id = models.ForeignKey(Acc, on_delete=models.DO_NOTHING)
    ad_id = models.ForeignKey(Admi, on_delete=models.DO_NOTHING)
    ul_id = models.ForeignKey(Ultb, on_delete=models.DO_NOTHING)
    comm = models.TextField(max_length=300)

class CName(models.Model):
    name = models.CharField(max_length=30)
    el_id = models.ForeignKey(Eleb, on_delete=models.DO_NOTHING)
    ul_id = models.ForeignKey(Ultb, on_delete=models.SET_NULL, null=True)
    ac_id = models.ForeignKey(Account, on_delete=models.SET_NULL, null=True)
